version: "3"
services:
  web:
    build: .
    container_name: web_v1 
    # external_links:
    #   - db-pg:db-pg
    command: gunicorn -w 1 -b 0.0.0.0:5000 --timeout 600 web_v1:app --reload
    environment:
        - FLASK_APP=web_v1.py
        - FLASK_DEBUG=1
        - PYTHONUNBUFFERED=TRUE
    ports:
      - "5011:5000"
    depends_on:
      - postgres_test

  postgres_test:
    container_name: db-pg
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - web_database:/var/lib/postgresql/data/

volumes:
  web_database: