version: "3"
services:
  flask_hack:
    container_name: web_v1  
    build: .
      
    command: gunicorn -w 1 -b 0.0.0.0:5000 --timeout 600 web_v1:app --reload
    environment:
        - FLASK_APP=web_v1.py
        - FLASK_DEBUG=1
        - PYTHONUNBUFFERED=TRUE
    ports:
        - '5011:5000'

